const nome1 = "luffy" 
let inimigos = 12
let tesouro = 10
let futasDoDiabo = 13
let felizLuffy = true

const nome2 = "nani"
let mapas = 3
let climasEstranhos = "primevera"
let satisfeita = true

const nome3 = "Sanji"
let pratos = 2
let piratasEnganados = 8
let fomeSanji = true


console.log (` Óla, meu nome é ${nome1} e eu tenho ${inimigos} inimigos; ${tesouro} tesouros, ${futasDoDiabo} frutas do diabo e estou felizLuffy. Ja o meu amigo se chama ${nome2} tem ${mapas} mapas, seu clima estranho é a  ${climasEstranhos} e esta satisfeito. Já o ${nome3} tem ${pratos} pratos, ${piratasEnganados} piratas enganados e tem fome sanji `)